Repository DevBadgers/starchive, pull requests merged in 2024-11, with the labels that each got.

#11 font, logo, 색상을 root에 추가
  FRONT/src/App.css
  FRONT/src/assets/logo/logo.svg
  FRONT/src/index.css
Labels: feature

#12 styled-components package 설정
  FRONT/package-lock.json
  FRONT/package.json
Labels: configure

#14 Navbar 컴포넌트
  FRONT/src/assets/icons/toggle-icon.svg
  FRONT/src/assets/images/example-profile.svg
  FRONT/src/components/Navbar/Navbar.styles.ts
  FRONT/src/components/Navbar/Navbar.tsx
Labels: feature

#13 PagingButton 컴포넌트 추가(#5)
  FRONT/src/assets/icons/left-arrow.svg
  FRONT/src/assets/icons/right-arrow.svg
  FRONT/src/components/PagingButton/PagingButton.styles.ts
  FRONT/src/components/PagingButton/PagingButton.tsx
Labels: feature

#17 파일 이름 styles.ts를 style.ts로 변경(#5)
  FRONT/src/components/Navbar/Navbar.style.ts
  FRONT/src/components/Navbar/Navbar.tsx
  FRONT/src/components/PagingButton/PagingButton.style.ts
  FRONT/src/components/PagingButton/PagingButton.tsx
Labels: feature

#16 버튼 공용 컴포넌트 구현
  FRONT/src/components/Button/Button.style.ts
  FRONT/src/components/Button/Button.tsx
  FRONT/src/types/aliases.d.ts
  FRONT/src/types/vite-env.d.ts
  FRONT/tsconfig.json
  FRONT/vite.config.ts
Labels: feature

#15 PostItem 컴포넌트 구현 (#5)
  FRONT/src/App.css
  FRONT/src/App.tsx
  FRONT/src/main.tsx
  FRONT/src/pages/Home/Home.tsx
  FRONT/src/pages/Home/components/PostItem/PostItem.style.ts
  FRONT/src/pages/Home/components/PostItem/PostItem.tsx
Labels: feature

#20 ArrowBtn 스타일 수정
  FRONT/src/components/PagingButton/PagingButton.style.ts
  FRONT/src/components/PagingButton/PagingButton.tsx
Labels: feature

#19 Aside 컴포넌트 (#5)
  FRONT/src/assets/icons/cancel-button.svg
  FRONT/src/assets/icons/category-toggle-button.svg
  FRONT/src/components/Aside/Aside.style.ts
  FRONT/src/components/Aside/Aside.tsx
  FRONT/src/components/Aside/category.example.json
  FRONT/src/components/Aside/components/CategoryNode.style.ts
  FRONT/src/components/Aside/components/CategoryNode.tsx
  FRONT/src/components/Aside/components/useCategoryNode.ts
  FRONT/src/components/Aside/types/Category.ts
  FRONT/src/components/Aside/useAside.ts
  FRONT/src/index.css
  FRONT/src/store/useAsideStore.ts
Labels: feature

#21 카테고리별 게시글 조회 API 구현 완료 (#5)
  BACK/nest-app/prisma/schema.prisma
  BACK/nest-app/src/app.module.ts
  BACK/nest-app/src/category/category.module.ts
  BACK/nest-app/src/category/category.service.spec.ts
  BACK/nest-app/src/category/category.service.ts
  BACK/nest-app/src/post/post.controller.spec.ts
  BACK/nest-app/src/post/post.controller.ts
  BACK/nest-app/src/post/post.module.ts
  BACK/nest-app/src/post/post.service.spec.ts
  BACK/nest-app/src/post/post.service.ts
  BACK/nest-app/src/prisma/prisma.module.ts
  BACK/nest-app/src/prisma/prisma.service.spec.ts
  BACK/nest-app/src/prisma/prisma.service.ts
Labels: feature

#23 메인 게시글 목록 페이지 레이아웃 (#5)
  FRONT/src/App.css
  FRONT/src/App.tsx
  FRONT/src/components/Button/Button.style.ts
  FRONT/src/components/Button/Button.tsx
  FRONT/src/pages/Home/Home.style.ts
  FRONT/src/pages/Home/Home.tsx
  FRONT/src/pages/Home/components/PostItem/PostItem.style.ts
  FRONT/src/types/aliases.d.ts
  FRONT/tests/setup.ts
  FRONT/tsconfig.json
  FRONT/vite.config.ts
Labels: feature

#22 카테고리 목록 조회 API 구현 (#5)
  BACK/spring-app/.gitignore
  BACK/spring-app/src/main/java/com/starchive/springapp/category/controller/CategoryController.java
  BACK/spring-app/src/main/java/com/starchive/springapp/category/domain/Category.java
  BACK/spring-app/src/main/java/com/starchive/springapp/category/dto/CategoryDto.java
  BACK/spring-app/src/main/java/com/starchive/springapp/category/dto/CategoryListTreeResponse.java
  BACK/spring-app/src/main/java/com/starchive/springapp/category/repository/CategoryRepository.java
  BACK/spring-app/src/main/java/com/starchive/springapp/category/service/CategoryService.java
  BACK/spring-app/src/test/java/com/starchive/springapp/category/controller/CategoryControllerTest.java
  BACK/spring-app/src/test/java/com/starchive/springapp/category/dto/CategoryDtoTest.java
  BACK/spring-app/src/test/java/com/starchive/springapp/category/dto/CategoryListTreeResponseTest.java
  BACK/spring-app/src/test/java/com/starchive/springapp/category/repository/CategoryRepositoryTest.java
  BACK/spring-app/src/test/java/com/starchive/springapp/category/service/CategoryServiceTest.java
Labels: feature

#25 Aside 컴포넌트 기능 구현 및 리팩토링 (#5)
  FRONT/src/App.tsx
  FRONT/src/components/Aside/Aside.style.ts
  FRONT/src/components/Aside/Aside.tsx
  FRONT/src/components/Aside/components/CategoryNode.style.ts
  FRONT/src/components/Aside/components/CategoryNode.tsx
  FRONT/src/components/Aside/components/useCategoryNode.ts
  FRONT/src/components/Aside/types/category.ts
  FRONT/src/components/Aside/useAside.ts
  FRONT/src/components/Navbar/Navbar.tsx
Labels: feature, refactor

#28 해쉬태그 조회 API 구현 (#5)
  BACK/spring-app/.gitignore
  BACK/spring-app/build.gradle
  BACK/spring-app/src/main/java/com/starchive/springapp/global/dto/ResponseDto.java
  BACK/spring-app/src/main/java/com/starchive/springapp/global/exception/GlobalExceptionHandler.java
  BACK/spring-app/src/main/java/com/starchive/springapp/hashtag/controller/HashTagController.java
  BACK/spring-app/src/main/java/com/starchive/springapp/hashtag/domain/HashTag.java
  BACK/spring-app/src/main/java/com/starchive/springapp/hashtag/dto/HashTagDto.java
  BACK/spring-app/src/main/java/com/starchive/springapp/hashtag/dto/HashTagRequest.java
  BACK/spring-app/src/main/java/com/starchive/springapp/hashtag/exception/HashTagNotFoundException.java
  BACK/spring-app/src/main/java/com/starchive/springapp/hashtag/repository/HashTagRepository.java
  BACK/spring-app/src/main/java/com/starchive/springapp/hashtag/service/HashTagService.java
  BACK/spring-app/src/test/java/com/starchive/springapp/hashtag/controller/HashTagControllerTest.java
  BACK/spring-app/src/test/java/com/starchive/springapp/hashtag/service/HashTagServiceTest.java
Labels: feature
