Repository DevBadgers/starchive, pull requests merged in 2024-12, with the labels that each got.

#32 메인 페이지 서버 데이터 연동 구현 (#5)
  FRONT/.gitignore
  FRONT/public/mock/posts
  FRONT/src/main.tsx
  FRONT/src/pages/Home/Home.style.ts
  FRONT/src/pages/Home/Home.tsx
  FRONT/src/pages/Home/components/PostItem/PostItem.style.ts
  FRONT/src/pages/Home/components/PostItem/PostItem.tsx
  FRONT/src/services/api.ts
  FRONT/src/services/postApi.ts
  FRONT/src/types/post.d.ts
Labels: feature

#33 게시글 조회에 페이징 추가 (#5)
  BACK/nest-app/prisma/schema.prisma
  BACK/nest-app/src/post/post.controller.ts
  BACK/nest-app/src/post/post.service.ts
Labels: feature

#34 카테고리 전체조회 반환 형식 변경 (#5)
  BACK/spring-app/src/main/java/com/starchive/springapp/category/controller/CategoryController.java
  BACK/spring-app/src/main/java/com/starchive/springapp/category/dto/CategoryListTreeResponse.java
  BACK/spring-app/src/main/java/com/starchive/springapp/category/service/CategoryService.java
  BACK/spring-app/src/main/resources/application.properties
  BACK/spring-app/src/test/java/com/starchive/springapp/SpringAppApplicationTests.java
  BACK/spring-app/src/test/java/com/starchive/springapp/category/controller/CategoryControllerTest.java
  BACK/spring-app/src/test/java/com/starchive/springapp/category/dto/CategoryDtoTest.java
  BACK/spring-app/src/test/java/com/starchive/springapp/category/dto/CategoryListTreeResponseTest.java
  BACK/spring-app/src/test/java/com/starchive/springapp/category/service/CategoryServiceTest.java
Labels: refactor

#35 카테고리 조회 api 연동 및 리팩토링 (#5)
  FRONT/public/mock/category.example.json
  FRONT/src/components/Aside/Aside.tsx
  FRONT/src/components/Aside/components/CategoryNode.tsx
  FRONT/src/components/Aside/useAside.ts
  FRONT/src/pages/Home/Home.tsx
  FRONT/src/services/categoryApi.ts
  FRONT/src/types/category.d.ts
Labels: feature, refactor

#37 태그별 글 조회 api 연동(#5)
  FRONT/src/components/TagWrapper/TagWrapper.style.ts
  FRONT/src/components/TagWrapper/TagWrapper.tsx
  FRONT/src/components/TagWrapper/useTag.ts
  FRONT/src/pages/Home/Home.tsx
  FRONT/src/services/tagApi.ts
Labels: feature

#39 카테고리별 태그리스트 조회 기능 구현 (#5)
  FRONT/src/components/TagWrapper/TagWrapper.tsx
  FRONT/src/components/TagWrapper/useTag.ts
  FRONT/src/pages/Home/Home.tsx
  FRONT/src/services/tagApi.ts
  FRONT/src/types/tag.d.ts
Labels: feature

#41 리팩토링 (#5)
  FRONT/src/App.tsx
  FRONT/src/components/Aside/Aside.tsx
  FRONT/src/components/Aside/components/CategoryNode.tsx
  FRONT/src/components/Aside/useAside.ts
  FRONT/src/components/Footer/Footer.tsx
  FRONT/src/components/Navbar/Navbar.tsx
  FRONT/src/components/PagingButton/PagingButton.tsx
  FRONT/src/components/TagWrapper/TagWrapper.tsx
  FRONT/src/components/TagWrapper/useTag.ts
  FRONT/src/pages/Home/Home.tsx
  FRONT/src/pages/Home/components/PostItem/PostItem.tsx
  FRONT/src/services/tagApi.ts
  FRONT/src/types/aliases.d.ts
  FRONT/tsconfig.json
  FRONT/vite.config.ts
Labels: refactor

#44 포스트 하단에 해시태그 표시 (#5)
  FRONT/src/pages/Home/Home.tsx
  FRONT/src/pages/Home/components/PostItem/PostItem.style.ts
  FRONT/src/pages/Home/components/PostItem/PostItem.tsx
  FRONT/src/types/post.d.ts
Labels: feature

#46 글 작성 페이지 레이아웃(#4)
  FRONT/src/App.tsx
  FRONT/src/assets/icons/drop-down-icon.svg
  FRONT/src/components/Footer/Footer.style.ts
  FRONT/src/pages/CreatePost/CreatePost.style.ts
  FRONT/src/pages/CreatePost/CreatePost.tsx
  FRONT/src/pages/CreatePost/components/CategorySelector/CategorySelector.style.ts
  FRONT/src/pages/CreatePost/components/CategorySelector/CategorySelector.tsx
Labels: feature
