Repository DevBadgers/starchive, pull requests merged in 2025-01, with the labels that each got.

#45 cors 헤더 추가
  BACK/spring-app/src/main/java/com/starchive/springapp/global/config/WebConfig.java
Labels: feature

#43 서버 CICD 구현
  .github/workflows/deploy.yml
  .github/workflows/nestjs-deploy.yml
  .github/workflows/nestjs.yml
  .github/workflows/spring-delploy.yml
  .github/workflows/spring-integration.yml
Labels: feature

#42 스프링 설정 파일 삭제
  BACK/spring-app/src/main/resources/application.properties
Labels: refactor

#47 마크다운 작성 기능 (#4)
  FRONT/package-lock.json
  FRONT/package.json
  FRONT/src/App.css
  FRONT/src/assets/icons/add-photo.svg
  FRONT/src/assets/icons/align-center.svg
  FRONT/src/assets/icons/align-left.svg
  FRONT/src/assets/icons/align-right.svg
  FRONT/src/components/Footer/Footer.style.ts
  FRONT/src/index.css
  FRONT/src/pages/CreatePost/CreatePost.style.ts
  FRONT/src/pages/CreatePost/CreatePost.tsx
  FRONT/src/pages/CreatePost/components/CategorySelector/CategorySelector.tsx
  FRONT/src/pages/CreatePost/components/EditorContainer/EditorContainer.style.ts
  FRONT/src/pages/CreatePost/components/EditorContainer/EditorContainer.tsx
  FRONT/src/pages/CreatePost/components/NicknamePasswordInput/NicknamePasswordInput.style.ts
  FRONT/src/pages/CreatePost/components/NicknamePasswordInput/NicknamePasswordInput.tsx
Labels: feature

#49 깃 허브 액션 수정
  .github/workflows/spring-delploy.yml
  .github/workflows/spring-integration.yml
Labels: feature

#52 글 작성 기능 구현 (#4)
  BACK/spring-app/build.gradle
  BACK/spring-app/src/main/java/com/starchive/springapp/category/controller/CategoryController.java
  BACK/spring-app/src/main/java/com/starchive/springapp/category/domain/Category.java
  BACK/spring-app/src/main/java/com/starchive/springapp/category/exception/CategoryNotFoundException.java
  BACK/spring-app/src/main/java/com/starchive/springapp/category/service/CategoryService.java
  BACK/spring-app/src/main/java/com/starchive/springapp/global/ErrorMessage.java
  BACK/spring-app/src/main/java/com/starchive/springapp/global/config/SchedulerConfig.java
  BACK/spring-app/src/main/java/com/starchive/springapp/global/exception/GlobalExceptionHandler.java
  BACK/spring-app/src/main/java/com/starchive/springapp/hashtag/domain/HashTag.java
  BACK/spring-app/src/main/java/com/starchive/springapp/hashtag/exception/HashTagNotFoundException.java
  BACK/spring-app/src/main/java/com/starchive/springapp/hashtag/repository/HashTagRepository.java
  BACK/spring-app/src/main/java/com/starchive/springapp/hashtag/service/HashTagService.java
  BACK/spring-app/src/main/java/com/starchive/springapp/image/controller/PostImageController.java
  BACK/spring-app/src/main/java/com/starchive/springapp/image/domain/PostImage.java
  BACK/spring-app/src/main/java/com/starchive/springapp/image/dto/PostImageDto.java
  BACK/spring-app/src/main/java/com/starchive/springapp/image/repository/PostImageRepository.java
  BACK/spring-app/src/main/java/com/starchive/springapp/image/service/PostImageService.java
  BACK/spring-app/src/main/java/com/starchive/springapp/post/controller/PostController.java
  BACK/spring-app/src/main/java/com/starchive/springapp/post/domain/Post.java
  BACK/spring-app/src/main/java/com/starchive/springapp/post/dto/PostCreateRequest.java
  BACK/spring-app/src/main/java/com/starchive/springapp/post/repository/PostRepository.java
  BACK/spring-app/src/main/java/com/starchive/springapp/post/service/PostService.java
  BACK/spring-app/src/main/java/com/starchive/springapp/posthashtag/domain/PostHashTag.java
  BACK/spring-app/src/main/java/com/starchive/springapp/posthashtag/service/PostHashTagService.java
  BACK/spring-app/src/main/java/com/starchive/springapp/s3/S3Config.java
  BACK/spring-app/src/main/java/com/starchive/springapp/s3/S3Service.java
  BACK/spring-app/src/test/java/com/starchive/springapp/category/controller/CategoryControllerTest.java
  BACK/spring-app/src/test/java/com/starchive/springapp/category/dto/CategoryDtoTest.java
  BACK/spring-app/src/test/java/com/starchive/springapp/category/service/CategoryServiceTest.java
  BACK/spring-app/src/test/java/com/starchive/springapp/hashtag/controller/HashTagControllerTest.java
  BACK/spring-app/src/test/java/com/starchive/springapp/hashtag/repository/HashTagRepositoryTest.java
  BACK/spring-app/src/test/java/com/starchive/springapp/hashtag/service/HashTagServiceTest.java
  BACK/spring-app/src/test/java/com/starchive/springapp/image/controller/PostImageControllerTest.java
  BACK/spring-app/src/test/java/com/starchive/springapp/image/service/PostImageServiceTest.java
  BACK/spring-app/src/test/java/com/starchive/springapp/post/controller/PostControllerTest.java
  BACK/spring-app/src/test/java/com/starchive/springapp/post/service/PostServiceTest.java
  BACK/spring-app/src/test/java/com/starchive/springapp/s3/S3MockConfig.java
  BACK/spring-app/src/test/java/com/starchive/springapp/s3/S3ServiceTest.java
Labels: feature

#53 태그 추가 구현(#4)
  FRONT/src/assets/icons/tag-add-icon.svg
  FRONT/src/assets/icons/tag-delete-icon.svg
  FRONT/src/pages/CreatePost/CreatePost.tsx
  FRONT/src/pages/CreatePost/components/TagWrapper/TagWrapper.style.ts
  FRONT/src/pages/CreatePost/components/TagWrapper/TagWrapper.tsx
Labels: feature

#54 버튼 클릭 시 에디터와 프리뷰를 전환하도록 변경 (#4)
  FRONT/package-lock.json
  FRONT/package.json
  FRONT/src/assets/icons/add-photo.svg
  FRONT/src/assets/icons/align-center.svg
  FRONT/src/assets/icons/align-left.svg
  FRONT/src/assets/icons/align-right.svg
  FRONT/src/assets/icons/toolbar/add-photo.svg
  FRONT/src/assets/icons/toolbar/bold.svg
  FRONT/src/assets/icons/toolbar/code.svg
  FRONT/src/assets/icons/toolbar/italic.svg
  FRONT/src/assets/icons/toolbar/link.svg
  FRONT/src/assets/icons/toolbar/quote.svg
  FRONT/src/assets/icons/toolbar/underline.svg
  FRONT/src/index.css
  FRONT/src/pages/CreatePost/CreatePost.tsx
  FRONT/src/pages/CreatePost/components/CategorySelector/CategorySelector.style.ts
  FRONT/src/pages/CreatePost/components/EditorContainer/EditorContainer.tsx
  FRONT/src/pages/CreatePost/components/MarkdownEditor/CodeBlock.tsx
  FRONT/src/pages/CreatePost/components/MarkdownEditor/MarkdownEditor.style.ts
  FRONT/src/pages/CreatePost/components/MarkdownEditor/MarkdownEditor.tsx
  FRONT/src/pages/CreatePost/components/MarkdownEditor/useMarkdownEditor.ts
  FRONT/src/pages/CreatePost/components/ToolBar/ToolBar.style.ts
  FRONT/src/pages/CreatePost/components/ToolBar/ToolBar.tsx
Labels: feature

#57 cors 허용 경로 수정
  BACK/spring-app/src/main/java/com/starchive/springapp/global/config/WebConfig.java
Labels: feature

#55 사진 업로드 api 연동(#4)
  FRONT/src/pages/CreatePost/components/MarkdownEditor/MarkdownEditor.style.ts
  FRONT/src/pages/CreatePost/components/MarkdownEditor/MarkdownEditor.tsx
  FRONT/src/pages/CreatePost/components/MarkdownEditor/useMarkdownEditor.ts
  FRONT/src/pages/CreatePost/components/ToolBar/ToolBar.tsx
  FRONT/src/services/api.ts
  FRONT/src/services/categoryApi.ts
  FRONT/src/services/createPostApi.ts
  FRONT/src/services/tagApi.ts
Labels: feature

#60 글 저장 기능 구현 (#4)
  FRONT/src/pages/CreatePost/CreatePost.tsx
  FRONT/src/pages/CreatePost/components/CategorySelector/CategorySelector.tsx
  FRONT/src/pages/CreatePost/components/MarkdownEditor/MarkdownEditor.tsx
  FRONT/src/pages/CreatePost/components/MarkdownEditor/useMarkdownEditor.ts
  FRONT/src/pages/CreatePost/components/NicknamePasswordInput/NicknamePasswordInput.tsx
  FRONT/src/pages/CreatePost/components/ToolBar/ToolBar.tsx
  FRONT/src/pages/CreatePost/hooks/useCreatePost.ts
  FRONT/src/pages/CreatePost/hooks/useMarkdownEditor.ts
  FRONT/src/services/api.ts
  FRONT/src/services/createPostApi.ts
  FRONT/src/types/post.d.ts
Labels: feature

#61 태그 저장 로직 추가 (#4)
  FRONT/src/pages/CreatePost/CreatePost.tsx
  FRONT/src/pages/CreatePost/components/TagWrapper/TagWrapper.tsx
  FRONT/src/pages/CreatePost/hooks/useCreatePost.ts
  FRONT/src/pages/CreatePost/hooks/useTag.ts
  FRONT/src/services/tagApi.ts
Labels: feature

#64 글 작성 및 저장 기능 수정 (#4)
  FRONT/src/assets/icons/toolbar/strikethrough.svg
  FRONT/src/assets/icons/toolbar/underline.svg
  FRONT/src/pages/CreatePost/components/ToolBar/ToolBar.style.ts
  FRONT/src/pages/CreatePost/components/ToolBar/ToolBar.tsx
  FRONT/src/pages/CreatePost/hooks/useMarkdownEditor.ts
  FRONT/src/pages/Home/Home.style.ts
  FRONT/src/pages/Home/Home.tsx
Labels: feature

#63 메인 브랜치 머지 시 실행되는 워크플로우 수정
  .github/workflows/deploy.yml
  .github/workflows/spring-delploy.yml
Labels: feature

#62 게시글 전체 조회 (#5)
  BACK/spring-app/src/main/java/com/starchive/springapp/category/dto/CategorySimpleDto.java
  BACK/spring-app/src/main/java/com/starchive/springapp/category/repository/CategoryRepository.java
  BACK/spring-app/src/main/java/com/starchive/springapp/category/service/CategoryService.java
  BACK/spring-app/src/main/java/com/starchive/springapp/global/ErrorMessage.java
  BACK/spring-app/src/main/java/com/starchive/springapp/global/exception/GlobalExceptionHandler.java
  BACK/spring-app/src/main/java/com/starchive/springapp/hashtag/dto/HashTagResponse.java
  BACK/spring-app/src/main/java/com/starchive/springapp/hashtag/repository/HashTagRepository.java
  BACK/spring-app/src/main/java/com/starchive/springapp/hashtag/service/HashTagService.java
  BACK/spring-app/src/main/java/com/starchive/springapp/post/controller/PostController.java
  BACK/spring-app/src/main/java/com/starchive/springapp/post/dto/PostDto.java
  BACK/spring-app/src/main/java/com/starchive/springapp/post/dto/PostListResponse.java
  BACK/spring-app/src/main/java/com/starchive/springapp/post/exception/PostNotFoundException.java
  BACK/spring-app/src/main/java/com/starchive/springapp/post/repository/PostRepository.java
  BACK/spring-app/src/main/java/com/starchive/springapp/post/service/PostService.java
  BACK/spring-app/src/main/java/com/starchive/springapp/posthashtag/domain/PostHashTag.java
  BACK/spring-app/src/main/java/com/starchive/springapp/posthashtag/service/PostHashTagService.java
  BACK/spring-app/src/test/java/com/starchive/springapp/post/service/PostServiceTest.java
Labels: feature

#68 메인 반영
  .github/workflows/deploy.yml
  .github/workflows/spring-delploy.yml
  BACK/spring-app/src/main/java/com/starchive/springapp/category/dto/CategorySimpleDto.java
  BACK/spring-app/src/main/java/com/starchive/springapp/category/repository/CategoryRepository.java
  BACK/spring-app/src/main/java/com/starchive/springapp/category/service/CategoryService.java
  BACK/spring-app/src/main/java/com/starchive/springapp/global/ErrorMessage.java
  BACK/spring-app/src/main/java/com/starchive/springapp/global/exception/GlobalExceptionHandler.java
  BACK/spring-app/src/main/java/com/starchive/springapp/hashtag/dto/HashTagResponse.java
  BACK/spring-app/src/main/java/com/starchive/springapp/hashtag/repository/HashTagRepository.java
  BACK/spring-app/src/main/java/com/starchive/springapp/hashtag/service/HashTagService.java
  BACK/spring-app/src/main/java/com/starchive/springapp/post/controller/PostController.java
  BACK/spring-app/src/main/java/com/starchive/springapp/post/dto/PostDto.java
  BACK/spring-app/src/main/java/com/starchive/springapp/post/dto/PostListResponse.java
  BACK/spring-app/src/main/java/com/starchive/springapp/post/dto/PostSimpleDto.java
  BACK/spring-app/src/main/java/com/starchive/springapp/post/exception/PostNotFoundException.java
  BACK/spring-app/src/main/java/com/starchive/springapp/post/repository/PostRepository.java
  BACK/spring-app/src/main/java/com/starchive/springapp/post/service/PostService.java
  BACK/spring-app/src/main/java/com/starchive/springapp/posthashtag/domain/PostHashTag.java
  BACK/spring-app/src/main/java/com/starchive/springapp/posthashtag/service/PostHashTagService.java
  BACK/spring-app/src/test/java/com/starchive/springapp/post/service/PostServiceTest.java
  FRONT/src/assets/icons/toolbar/strikethrough.svg
  FRONT/src/assets/icons/toolbar/underline.svg
  FRONT/src/pages/CreatePost/CreatePost.tsx
  FRONT/src/pages/CreatePost/components/TagWrapper/TagWrapper.tsx
  FRONT/src/pages/CreatePost/components/ToolBar/ToolBar.style.ts
  FRONT/src/pages/CreatePost/components/ToolBar/ToolBar.tsx
  FRONT/src/pages/CreatePost/hooks/useCreatePost.ts
  FRONT/src/pages/CreatePost/hooks/useMarkdownEditor.ts
  FRONT/src/pages/CreatePost/hooks/useTag.ts
  FRONT/src/pages/Home/Home.style.ts
  FRONT/src/pages/Home/Home.tsx
  FRONT/src/services/tagApi.ts
Labels: feature

#65 Toast 컴포넌트 및 상태 관리 구현 (#4)
  FRONT/src/App.tsx
  FRONT/src/components/Aside/useAside.ts
  FRONT/src/pages/CreatePost/components/Toast/Toast.style.ts
  FRONT/src/pages/CreatePost/components/Toast/Toast.tsx
  FRONT/src/pages/CreatePost/components/Toast/useToast.ts
  FRONT/src/pages/CreatePost/hooks/useCreatePost.ts
  FRONT/src/stores/useAsideStore.ts
  FRONT/src/stores/useLoadingStore.ts
  FRONT/src/stores/useToastStore.ts
Labels: feature

#66 글 상세 조회 페이지 구현 (#6)
  FRONT/src/App.tsx
  FRONT/src/pages/Post/Post.style.ts
  FRONT/src/pages/Post/Post.tsx
Labels: feature

#72 게시글 상세 조회 api 연동(#6)
  FRONT/src/App.tsx
  FRONT/src/components/TagWrapper/useTag.ts
  FRONT/src/pages/Home/Home.tsx
  FRONT/src/pages/Home/components/PostItem/PostItem.style.ts
  FRONT/src/pages/Home/components/PostItem/PostItem.tsx
  FRONT/src/pages/Post/Post.style.ts
  FRONT/src/pages/Post/Post.tsx
  FRONT/src/services/postApi.ts
  FRONT/src/types/aliases.d.ts
  FRONT/src/types/post.d.ts
  FRONT/vite.config.ts
Labels: feature

#73 페이징 버그 수정(#69)
  FRONT/src/components/TagWrapper/useTag.ts
  FRONT/src/pages/Home/Home.tsx
Labels: bug

#74 카테고리 관리 컴포넌트 구현 (#8)
  FRONT/package-lock.json
  FRONT/package.json
  FRONT/src/assets/icons/add-icon.svg
  FRONT/src/assets/icons/edit-icon.svg
  FRONT/src/assets/icons/trash-icon.svg
  FRONT/src/components/IconButton/IconButton.style.ts
  FRONT/src/components/IconButton/IconButton.tsx
  FRONT/src/pages/MyPage/components/CategoryManagement/CategoryManagement.style.ts
  FRONT/src/pages/MyPage/components/CategoryManagement/CategoryManagement.tsx
  FRONT/src/pages/MyPage/components/CategoryNode/CategoryNode.style.ts
  FRONT/src/pages/MyPage/components/CategoryNode/CategoryNode.tsx
  FRONT/src/pages/MyPage/hooks/useCategoryManagement.ts
  FRONT/vite.config.ts
Labels: feature

#75 카테고리 없은 게시글 조회(#8)
  FRONT/src/components/Aside/Aside.tsx
  FRONT/src/pages/CreatePost/components/CategorySelector/CategorySelector.tsx
Labels: feature

#76 데이터베이스 초기화시 사용되는 카테고리 테이블명 수정 (#8)
  BACK/spring-app/src/main/resources/data.sql
Labels: bug

#78 feat: 브랜치 구별해서 배포 되도록 수정
  .github/workflows/spring-delploy.yml
Labels: feature

#79 메인 반영
  .github/workflows/spring-delploy.yml
  BACK/spring-app/src/main/java/com/starchive/springapp/category/controller/CategoryController.java
  BACK/spring-app/src/main/java/com/starchive/springapp/category/domain/Category.java
  BACK/spring-app/src/main/java/com/starchive/springapp/category/dto/CategoryCreateRequest.java
  BACK/spring-app/src/main/java/com/starchive/springapp/category/dto/CategoryUpdateRequest.java
  BACK/spring-app/src/main/java/com/starchive/springapp/category/dto/CategoryUpdateResponse.java
  BACK/spring-app/src/main/java/com/starchive/springapp/category/exception/CategoryAlreadyExistsException.java
  BACK/spring-app/src/main/java/com/starchive/springapp/category/repository/CategoryRepository.java
  BACK/spring-app/src/main/java/com/starchive/springapp/category/service/CategoryService.java
  BACK/spring-app/src/main/java/com/starchive/springapp/global/ErrorMessage.java
  BACK/spring-app/src/main/java/com/starchive/springapp/global/dto/ErrorResult.java
  BACK/spring-app/src/main/java/com/starchive/springapp/global/exception/GlobalExceptionHandler.java
  BACK/spring-app/src/main/java/com/starchive/springapp/post/repository/PostRepository.java
  BACK/spring-app/src/main/resources/data.sql
  BACK/spring-app/src/test/java/com/starchive/springapp/category/dto/CategoryDtoTest.java
  BACK/spring-app/src/test/java/com/starchive/springapp/category/service/CategoryServiceTest.java
  FRONT/package-lock.json
  FRONT/package.json
  FRONT/src/App.tsx
  FRONT/src/assets/icons/add-icon.svg
  FRONT/src/assets/icons/edit-icon.svg
  FRONT/src/assets/icons/trash-icon.svg
  FRONT/src/components/Aside/Aside.tsx
  FRONT/src/components/Aside/useAside.ts
  FRONT/src/components/IconButton/IconButton.style.ts
  FRONT/src/components/IconButton/IconButton.tsx
  FRONT/src/components/TagWrapper/TagWrapper.style.ts
  FRONT/src/components/TagWrapper/TagWrapper.tsx
  FRONT/src/components/TagWrapper/useTag.ts
  FRONT/src/pages/CreatePost/components/CategorySelector/CategorySelector.tsx
  FRONT/src/pages/CreatePost/components/Toast/Toast.style.ts
  FRONT/src/pages/CreatePost/components/Toast/Toast.tsx
  FRONT/src/pages/CreatePost/components/Toast/useToast.ts
  FRONT/src/pages/CreatePost/hooks/useCreatePost.ts
  FRONT/src/pages/Home/Home.style.ts
  FRONT/src/pages/Home/Home.tsx
  FRONT/src/pages/Home/components/PostItem/PostItem.style.ts
  FRONT/src/pages/Home/components/PostItem/PostItem.tsx
  FRONT/src/pages/MyPage/components/CategoryManagement/CategoryManagement.style.ts
  FRONT/src/pages/MyPage/components/CategoryManagement/CategoryManagement.tsx
  FRONT/src/pages/MyPage/components/CategoryNode/CategoryNode.style.ts
  FRONT/src/pages/MyPage/components/CategoryNode/CategoryNode.tsx
  FRONT/src/pages/MyPage/hooks/useCategoryManagement.ts
  FRONT/src/pages/Post/Post.style.ts
  FRONT/src/pages/Post/Post.tsx
  FRONT/src/services/api.ts
  FRONT/src/services/postApi.ts
  FRONT/src/stores/useAsideStore.ts
  FRONT/src/stores/useLoadingStore.ts
  FRONT/src/stores/useToastStore.ts
  FRONT/src/types/aliases.d.ts
  FRONT/src/types/post.d.ts
  FRONT/vite.config.ts
Labels: feature
